version: '3.4'

services:
  masa.pm.service.admin:
    image: ${DOCKER_REGISTRY-}masapmserviceadmin
    build:
      context: .
      dockerfile: src/Services/MASA.PM.Service.Admin/Dockerfile

  masa.pm.web.admin:
    image: ${DOCKER_REGISTRY-}masapmuiadmin
    build:
      context: .
      dockerfile: src/Web/MASA.PM.Web.Admin/Dockerfile

