<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>    
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>lonsid-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="$(DotnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="$(DotnetVersion)" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="$(DotnetVersion)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="$(DotnetVersion)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MASA.PM.Infrastructure.EFCore\MASA.PM.Infrastructure.EFCore.csproj" />
  </ItemGroup>

</Project>
