apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: local-secret-store
  namespace: default
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./localfile/LocalConfig.json
  - name: nestedSeparator
    value: ":"
  - name: multiValued
    value: "true"